### ISSUE TITLE
Error: No default engine was specified and no extension was provided

### ISSUE THREAD

**Issue by himanshu64** [saurabharch/push-rest#17]
``Server started on port 3000
MongoDB Connected
Error: No default engine was specified and no extension was provided.
    at new View (D:\webpush\node_modules\express\lib\view.js:61:11)
    at Function.render (D:\webpush\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (D:\webpush\node_modules\express\lib\response.js:1012:7)
    at D:\webpush\server.js:87:9
    at Layer.handle_error (D:\webpush\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (D:\webpush\node_modules\express\lib\router\index.js:315:13)
    at D:\webpush\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\webpush\node_modules\express\lib\router\index.js:335:12)
    at next (D:\webpush\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (D:\webpush\node_modules\express\lib\router\layer.js:73:5)
    at trim_prefix (D:\webpush\node_modules\express\lib\router\index.js:315:13)
    at D:\webpush\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\webpush\node_modules\express\lib\router\index.js:335:12)
    at next (D:\webpush\node_modules\express\lib\router\index.js:275:10)
    at D:\webpush\server.js:66:5
    at Layer.handle [as handle_request] (D:\webpush\node_modules\express\lib\router\layer.js:95:5)

**Comment by saurabharch** [comment]
Please add any one of the handlebars or pug or ejs html engine For rendering index.html page with express for more refer to [rollout](https://github.com/saurabharch/rollout) project

**Comment by saurabharch** [comment]
Closed
